fix: speos-optislang WF failing (#150)

diff --git a/.github/workflows/speos-optislang.yml b/.github/workflows/speos-optislang.yml
--- a/.github/workflows/speos-optislang.yml
+++ b/.github/workflows/speos-optislang.yml
@@ -65,6 +65,19 @@ jobs:
           ANSYS_RELEASE_COMPACT="${ANSYS_RELEASE_SHORT//./}"
           echo "ANSYS_RELEASE_COMPACT=$ANSYS_RELEASE_COMPACT" >> $GITHUB_ENV
 
+      - name: Modify ansyslmd.ini file
+        shell: bash
+        run: |
+          # Define the path to the license file
+          LIC_FILE_PATH="C:\Program Files\ANSYS Inc\Shared Files\licensing\ansyslmd.ini"
+          # Verify that the file exists
+          if [ ! -f "$LIC_FILE_PATH" ]; then
+            echo "License file not found at $LIC_FILE_PATH"
+            exit 1
+          fi
+          # REPLACE the line starting with SERVER by something like: SERVER=1055@XX.XXX.XX.XX
+          sed -i "s|^SERVER=.*|SERVER=${{ env.ANSYSLMD_LICENSE_FILE }}|" "$LIC_FILE_PATH"
+
       - name: Install dependencies
         shell: bash
         run: |
